/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_dailylime_torchcvhelloworld_MainActivity */

#ifndef _Included_kr_dailylime_torchcvhelloworld_MainActivity
#define _Included_kr_dailylime_torchcvhelloworld_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef kr_dailylime_torchcvhelloworld_MainActivity_CAMERA_PERMISSION_REQUEST_CODE
#define kr_dailylime_torchcvhelloworld_MainActivity_CAMERA_PERMISSION_REQUEST_CODE 200L
/*
 * Class:     kr_dailylime_torchcvhelloworld_MainActivity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_kr_dailylime_torchcvhelloworld_MainActivity_ConvertRGBtoGray
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     kr_dailylime_torchcvhelloworld_MainActivity
 * Method:    InferMobileNetClassifier
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_kr_dailylime_torchcvhelloworld_MainActivity_InferMobileNetClassifier
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     kr_dailylime_torchcvhelloworld_MainActivity
 * Method:    InitializeClassifier
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kr_dailylime_torchcvhelloworld_MainActivity_InitializeClassifier
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
